spring:
  datasource:
      druid:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://localhost/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        initial-size: 3
        min-idle: 3
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT NOW()"
        test-on-borrow: false
        test-on-return: false
        filter:
          stat:
            enabled: false
  main:
    banner-mode: "off"
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  mvc:
    favicon:
      enabled: false
  http:
    encoding:
      force: true
  freemarker:
    cache: true
    suffix: .ftl
    settings:
      template_update_delay: "0"
      number_format: "#"
server:
  error:
    whitelabel:
      enabled: false